---
driver:
  name: ec2
  tags:
    Name: kitchen-castor
  iam_profile_name: aws-rds-readonly-download-logs-role
  subnet_id: subnet-2ca9d775
  shared_credentials_profile: kitchen
  availability_zone: a
  security_group_ids: ['sg-f7fa1891']
  instance_type: t2.micro
  require_chef_omnibus: true
  associate_public_ip: true
  aws_ssh_key_id: ls.deployer
  block_device_mappings:
    - device_name: /dev/sda1
      ebs:
        volume_size: 8
        delete_on_termination: true

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
    driver:
      image_id: ami-96a818fe
    transport:
      name: sftp
      username: centos
      ssh_key: ~/.ssh/deployer

  - name: ubuntu-14.04
    driver:
      image_id: ami-86562dee
    transport:
      name: sftp
      username: ubuntu
      ssh_key: ~/.ssh/deployer

suites:
  - name: default
    run_list:
      - recipe[castor]

  - name: only_slowquery
    run_list:
      - recipe[castor]
    attributes:
      castor:
        logs_to_process: ['slowquery']
