---
driver:
  name: ec2
  tags:
    Name: kitchen-castor
  iam_profile_name: aws-rds-readonly-download-logs-role
  subnet_id: subnet-1234
  shared_credentials_profile: kitchen
  availability_zone: a
  security_group_ids: ['sg-1234', 'sg-1234', 'sg-1234', 'sg-1234']
  instance_type: t2.micro
  require_chef_omnibus: true
  associate_public_ip: true
  aws_ssh_key_id: deploy_key
  block_device_mappings:
    - ebs_device_name: /dev/sda1
      ebs_volume_size: 8
      ebs_delete_on_termination: true

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
    driver:
      image_id: ami-96a818fe
    transport:
      username: centos
      ssh_key: ~/.ssh/id_rsa

  - name: ubuntu-14.04
    driver:
      image_id: ami-86562dee
    transport:
      username: ubuntu
      ssh_key: ~/.ssh/id_rsa

suites:
  - name: default
    run_list:
      - recipe[castor]
