Metrics/LineLength:
  Max: 200

Style/HashSyntax:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
