name             'castor'
maintainer       'lightspeed POS, Inc.'
maintainer_email 'retailops@lightspeedpos.com'
license          'MIT'
description      'Installs/Configures castor'
long_description 'Installs/Configures castor'
version          '0.4.1'

depends          'python', '>= 0.9.0'
depends          'logrotate', '>= 1.7.0'
