default['castor']['version'] = '1.0.0'
default['castor']['user'] = 'castor'
default['castor']['group'] = 'castor'
default['castor']['base_dir'] = '/opt/castor'
default['castor']['iam_profile_name'] = 'aws-rds-readonly-download-logs-role'
